export const ESTADO_SESION="ESTADO_SESION";
export const MENSAJE_ALERTA="MENSAJE_ALERTA";
export const CERRAR_ALERTA="CERRAR_ALERTA";
export const CREAR_USUARIO="CREAR_USUARIO";
export const INICIAR_SESION="INICIAR_SESION";
export const CREAR_PROBLEMA="CREAR_PROBLEMA";
export const EDITAR_USUARIO="EDITAR_USUARIO";